### PR TITLE
Youtube Clone project: feature branch

### PR DESCRIPTION
**Pull request by nyatindopatrick**
## Youtube Clone Project: Feature branch
In this project:
- We created a responsive navigation bar
- We embedded a youtube video in the page
- We created thumbnails sidebar
-We added comments section
-We created a footer

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @nyatindopatrick @Eshy10  , 👋 You have done a great job in this project 👏 

* [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] Fix HTML validation issues
image
* [ ] Check usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) elements. They should be "appropriately sized and positioned" (as described in Odin project description) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright)

> your live demo not working ⚒ check that


----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by Kyle-Law** [comment]
**Feedbacks from a classmate - Kyle Law**
1) In your terminal, `touch .gitignore` and put .DS_Store inside to ignore the unnecessary file; `rm .DS_Store` to remove the file; `ls -a` to see hidden files inside the directory. 
2) delete `frameborder` property

**Review by fatymahmed — COMMENTED** [review]
## Hi guys 
Great job on using gitignore!

**Sidebar Recommended videos**
- According to the requirements in pathwright, you should have recommended video's thumbnail preview but I can't see yours, check [requirement screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_thumbnail_requirement.png)

- You should check HTML markup with a validator as described in the [pathwright requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png), your project has some errors, please fix those.

Your HTML Markup errors
Screenshot

Your webpage doesn't have the recommended videos sidebar
Screenshot

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Please make the above changes and request for another code review.

## Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help_

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team   
#### Great Job working on last review requirements, but there is one more thing required. 

### Page structure
- [ ] Please the **Share** should be a button lets fix that.


### Make changes and submit another code review request.
*Happy coding*

**Comment by rOluochKe** [comment]
@nyatindopatrick and @Eshy10 Good job for reaching this far. You have made some changes required from previous reviews. However, you to make a change

- Fix the html validator, [refer from this link](https://validator.w3.org/#validate_by_upload)
button

Once the change is made, resubmit and that should pass the project for approval. Best of luck.

**Review by nikasulo — APPROVED** [review]
# Fantastic job @Kyle-Law and @nyatindopatrick! :rocket: 
This is a beautiful project. Your readme is descriptive, your HTML is well written, your PR is descriptive and your site looks sweet! Congrats :medal_military: 

Please merge and keep moving forward with your level of commitment and drive, see you at the top! :100: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
